# vehicle parameters
speed_low: 0
speed_high: 5
cav_route: "route_CAV_abctest"
cav_initial_lane: "EG_1_3_1_1"
cav_initial_position: 0

# sumo parameters
sumo_net_file_path: "examples/maps/Mcity/mcity_sumo_new3.net.xml"
sumo_config_file_path: "examples/maps/Mcity/mcity.sumocfg"
sumo_tls_addition_info_file_path: "examples/configs/Mcity_tls_additional_param.yaml"
sumo_step_length: 0.1

# Autoware PCD map information
PCDMap_origin_gps_latlon: [42.2992191838, -83.6981841635]
PCDMap_origin_gps_utm: [277584.8373869159, 4686524.9512347495]
PCDMap_origin_local: [87.72738691592589, 6.201234749518335]
PCDMap_SUMOMap_offset: [0,0,-34.5]
PCDMap_realworld_offset: [0, 0, -304.5]

# ros nodes
AR_senders_list:
  - "sumo_bvs_after_perception"
AR_receivers_list:
  - "autoware_localization"
