MOBIL_lc_flag: True
stochastic_acc_flag: False
sumo_net_file_path: "maps/Mcity_safetest_complete_carla/mcity.net.xml"
sumo_cfg_file_path: "maps/Mcity_safetest_complete_carla/mcity.sumocfg"
drive_rule: "righthand"

adversity_sampling_probability: 1e-9
adversity_cfg:
  # vehicle:
  #   roundabout_cutin:
  #     _target_: terasim_nde_nade.adversity.vehicles.lanechange_adversity.LanechangeAdversity
  #     _convert_: 'all'
  #     location: 'roundabout'
  #     ego_type: 'vehicle'
  #     probability: 2.3123152310029683e-05
  #     predicted_collision_type: "roundabout_cutin"
    
  #   roundabout_rearend:
  #     _target_: terasim_nde_nade.adversity.vehicles.leader_adversity.LeaderAdversity
  #     _convert_: 'all'
  #     location: 'roundabout'
  #     ego_type: 'vehicle'
  #     probability: 1.8383121748678325e-10
  #     predicted_collision_type: "roundabout_rearend"

  #   roundabout_fail_to_yield:
  #     _target_: terasim_nde_nade.adversity.vehicles.trafficrule_adversity.TrafficRuleAdversity
  #     _convert_: 'all'
  #     location: 'roundabout'
  #     ego_type: 'vehicle'
  #     probability: 0.0005025411072000003
  #     predicted_collision_type: "roundabout_fail_to_yield"

  #   # roundabout_neglect_conflict_lead:
  #   #   _target_: terasim_nde_nade.adversity.roundabout_cutin_adversity.RoundaboutCutinAdversity
  #   #   _convert_: 'all'
  #   #   location: 'roundabout'
  #   #   ego_type: 'vehicle'
  #   #   probability: 0.00027119028871789013

  #   # highway_cutin_abort:
  #   #   _target_: terasim_nde_nade.adversity.vehicles.LanechangeAbortAdversity
  #   #   _convert_: 'all'
  #   #   location: 'highway'
  #   #   ego_type: 'vehicle'
  #   #   probability: 1e-5 # 0.8783674048511999
  #   #   predicted_collision_type: "highway_cutin"

  #   highway_cutin:
  #     _target_: terasim_nde_nade.adversity.vehicles.lanechange_adversity.LanechangeAdversity
  #     _convert_: 'all'
  #     location: 'highway'
  #     ego_type: 'vehicle'
  #     probability: 3.1996225726187704e-05
  #     predicted_collision_type: "highway_cutin"

  #   highway_rearend:
  #     _target_: terasim_nde_nade.adversity.vehicles.leader_adversity.LeaderAdversity
  #     _convert_: 'all'
  #     location: 'highway'
  #     ego_type: 'vehicle'
  #     probability: 0 # 0.8783674048511999
  #     predicted_collision_type: "highway_rearend"

  #   intersection_cutin:
  #     _target_: terasim_nde_nade.adversity.vehicles.lanechange_adversity.LanechangeAdversity
  #     _convert_: 'all'
  #     location: 'intersection'
  #     ego_type: 'vehicle'
  #     probability: 6.694592721399203e-05
  #     predicted_collision_type: "intersection_cutin"

  #   intersection_rearend:
  #     _target_: terasim_nde_nade.adversity.vehicles.leader_adversity.LeaderAdversity
  #     _convert_: 'all'
  #     location: 'intersection'
  #     ego_type: 'vehicle'
  #     probability: 0.00017365940078885788
  #     predicted_collision_type: "intersection_rearend"

  #   intersection_headon:
  #     _target_: terasim_nde_nade.adversity.vehicles.headon_adversity.HeadonAdversity
  #     _convert_: 'all'
  #     location: 'intersection'
  #     ego_type: 'vehicle'
  #     probability: 1.0663168272664859e-08
  #     predicted_collision_type: "intersection_headon"

  #   intersection_tfl:
  #     _target_: terasim_nde_nade.adversity.vehicles.trafficrule_adversity.TrafficRuleAdversity
  #     _convert_: 'all'
  #     location: 'intersection'
  #     ego_type: 'vehicle'
  #     probability: 0.010141902545438387
  #     predicted_collision_type: "intersection_tfl"

  #   # intersection_neglect_conflict_lead:
  #   #   _target_: terasim_nde_nade.adversity.roundabout_cutin_adversity.RoundaboutCutinAdversity
  #   #   _convert_: 'all'
  #   #   location: 'roundabout'
  #   #   ego_type: 'vehicle'
  #   #   probability: 0.015050715723004704

  # vulnerable_road_user:
  #   jaywalking:
  #     _target_: terasim_nde_nade.adversity.vru.jaywalking_adversity.JaywalkingAdversity
  #     _convert_: 'all'
  #     location: 'crosswalk'
  #     ego_type: 'vulnerable_road_user'
  #     probability: 0.1
  #     predicted_collision_type: "intersection_jaywalking"

  #   runningredlight:
  #     _target_: terasim_nde_nade.adversity.vru.runningredlight_adversity.RunningRedLightAdversity
  #     _convert_: 'all'
  #     location: 'crosswalk'
  #     ego_type: 'vulnerable_road_user'
  #     probability: 0.1
  #     predicted_collision_type: "intersection_runningredlight"

  #   stopcrossing:
  #     _target_: terasim_nde_nade.adversity.vru.stopcrossing_adversity.StopCrossingAdversity
  #     _convert_: 'all'
  #     location: 'crosswalk'
  #     ego_type: 'vulnerable_road_user'
  #     probability: 0.1
  #     predicted_collision_type: "intersection_stopcrossing"

  static:
    # construction:
    #   _target_: terasim_nde_nade.adversity.ConstructionAdversity
    #   _convert_: 'all'
    #   lane_id: "" # "379459612#1_0"

    # collision:
    #   _target_: terasim_nde_nade.adversity.CollisionAdversity
    #   _convert_: 'all'
    #   lane_id: "EG_1_3_1.61_0" # "379459612#1_2"
    #   lane_position: 40 
    #   start_time: 900
    #   end_time: 2000
    #   object_type:
    #     - "passenger"
    #     - "truck"
    #   other_settings:
    #     collision_type: "side_swipe" # rear_end, side_swipe
        

    # stalled_object:
    #   _target_: terasim_nde_nade.adversity.StalledObjectAdversity
    #   _convert_: 'all'
    #   lane_id: "EG_1_3_1.61_0" # "379459612#1_0"
    #   lane_position: 20
    #   start_time: 900
    #   end_time: 2000
    #   object_type: "police"

    dynamic_object:
      _target_: terasim_nde_nade.adversity.DynamicObjectAdversity
      _convert_: 'all'
      lane_id: "EG_35_1_14_0" # "379459612#1_0"
      lane_position: 0
      start_time: 601
      end_time: 2000
      object_type: "police" 

CAV_cfg:
  route: ["EG_35_1_14", "EG_1_3_1", "EG_1_3_1.61", "EG_1_3_1.136", "EG_34_1_24", "EG_34_1_3", "gneE0", "EG_4_1_1", "EG_10_1_1", "EG_15_1_17", "EG_15_1_1", "EG_16_23_1", "EG_17_1_1", "EG_17_1_1.17", "EG_14_2_1", "EG_14_2_1.5", "EG_14_2_1.24", "EG_9_1_1", "EG_9_1_1.28", "EG_21_1_1", "EG_21_1_5", "EG_20_1_11", "EG_29_1_1", "EG_35_1_14"] # list of SUMO edges (example for Mcity)
  type: "NDE_HIGHWAY"
  cache_radius: 100
  control_radius: 50